# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # General Vagrant VM configuration.
  config.vm.box = "geerlingguy/ubuntu2004"
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :virtualbox do |v|
    v.memory = 512
    v.linked_clone = true
  end

  # Application server 1
  config.vm.define "inventory1" do |app|
    app.vm.hostname = "inventory1.test"
    app.vm.network :private_network, ip: "192.168.28.71"
  end 

  # Application server 2
  config.vm.define "inventory2" do |app|
    app.vm.hostname = "inventory2.test"
    app.vm.network :private_network, ip: "192.168.28.72"
  end 
end
